### ISSUE TITLE
pure carbon copy of 1337x Bot.

### ISSUE THREAD

**Issue by kekkodance** [miatoszs/torrentbot#1]
excuse me, but you took [this](https://github.com/brandongallagher1999/1337x-Bot/) repo, added some stuff to it without credits, hosted a bot that got VERIFIED unlike its original counterpart, and you want PayPal money too from this? The codebase was written by Cryptoguys AKA brandongallagher1999, and you took it, modified it a bit and published it with absolutely no recognition.

Closing this issue will only prove my point and add further proof to report to Discord's bots management.

**Comment by miatoszs** [comment]
this is not a pure carbon copy of the 1337x Bot, I used a part of it, this is the essence of open source

**Comment by pryme-svg** [comment]
>  I used a part of it

the original repository required the [License notice](https://github.com/brandongallagher1999/1337x-Bot/blob/production/LICENSE) to be included in "all copies of the software"
